#!/bin/bash

# Check if base-devel is already installed
if pacman -Qi base-devel | grep -q "installed"; then
    echo "base-devel is already installed."
else
    # Install base-devel using pacman
    sudo pacman -S --needed base-devel
fi

# Set the repository path to the current working directory
REPO_PATH=$(pwd)

# Get a list of folders in the repository
FOLDERS=($(find "${REPO_PATH}" -type d))

# Iterate over each folder and run "make clean install"
for folder in "${FOLDERS[@]}"; do
    cd "${folder}"
    rm -rf config.h
    sudo make -k clean install
done
clear

echo "dwm and its packages have been installed correctly."
sleep 2
clear

# Ask if you want to use/enable lightdm
read -p "Do you want to install/enable lightdm as your display manager? (y/n) " response

if [[ $response == y ]]; then
    sudo pacman -S lightdm || { echo "Error installing lighdm"; exit 1; } 
    sudo systemctl enable lightdm.service || { echo "Error enabling lightdm"; exit 1; }
    echo "lightdm has been installed/enabled succesfully."
else
    echo "lightdm has not been enabled/installed."
fi

sleep 2
clear

# Create the /usr/share/xsessions directory if it doesn't already exist,
# then copy dwm.desktop into it if the user agrees to do so.
read -p "Do you want to copy dwm.desktop so it shows up in your display manager? (y/n): " response

if [[ $response =~ ^[Yy]$ ]]; then
    mkdir -p /usr/share/xsessions && sudo cp ${REPO_PATH}/dwm.desktop /usr/share/xsessions/ || { echo "Erro Copying dwm.desktop"; exit 1; }
    echo "dwm.desktop >> /usr/share/xsessions/dwm.desktop."
else
    echo "dwm.dektop has not been copied to /usr/share/xsessions."
fi

sleep 2
clear

echo "Thanks for using my script, have fun https://github.com/DAnaselo"
